/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import NativeAd from "./TJ/NativeAd"
import ButtonScale from "./TJ/Promo/script/ButtonScale"
import PromoItem from "./TJ/Promo/script/PromoItem"
import P405 from "./TJ/Promo/script/P405"
import P201 from "./TJ/Promo/script/P201"
import LwgInit from "./script/Lwg/LwgInit"
import P402 from "./TJ/Promo/script/P402"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1280;
    static height:number=720;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/LwgInit.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("TJ/NativeAd.ts",NativeAd);
        reg("TJ/Promo/script/ButtonScale.ts",ButtonScale);
        reg("TJ/Promo/script/PromoItem.ts",PromoItem);
        reg("TJ/Promo/script/P405.ts",P405);
        reg("TJ/Promo/script/P201.ts",P201);
        reg("script/Lwg/LwgInit.ts",LwgInit);
        reg("TJ/Promo/script/P402.ts",P402);
    }
}
GameConfig.init();